--Sequence
CREATE SEQUENCE SQ1 AS INT
 START WITH 100
 INCREMENT BY 25
 MINVALUE 100
 MAXVALUE 200
 CYCLE
 CACHE 10
 GO SELECT NEXT VALUE FOR SQ1  SELECT NEXT VALUE FOR SQ1   SELECT NEXT VALUE FOR SQ1    SELECT NEXT VALUE FOR SQ1